<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<a href="{loginUrl}">Login</a> to comment' => '<a href="{loginUrl}">Login</a> om te reageren',
    '<a href="{loginUrl}">Login</a> to view comments' => '<a href="{loginUrl}">Login</a> om reacties te zien',
    'Accept' => 'Accepteer',
    'Accepted' => 'Geaccepteerd',
    'Body' => 'Inhoud',
    'Can accept, reject, update or delete all comments' => 'Kan reacties accepteren, afwijzen, bijwerken of wissen',
    'Comment cannot be blank' => 'Reactie mag niet blanco zijn',
    'Comments' => 'Reacties',
    'Comments ({n,number})' => 'Reacties ({n,number})',
    'Create comment' => 'Reactie aanmaken',
    'Created At' => 'Ingestuurd op',
    'Created By' => 'Ingestuurd door',
    'Delete' => 'Wissen',
    'Delete comment' => 'Reactie wissen',
    'Delete self-created comment' => 'Eigen reactie wissen',
    'Deleting {nick}\'s Comment. Are you sure?' => '{nick}\'s reactie wissen. Zeker weten?',
    'Edit' => 'Bewerken',
    'Empty' => 'Leeg',
    'Manage comments' => 'Reacties beheren',
    'My comment...' => 'Mijn reactie...',
    'My reply...' => 'Mijn antwoord...',
    'Next' => 'Volgende',
    'Pending' => 'Wachtrij',
    'Previous' => 'Vorige',
    'Reject' => 'Afwijzen',
    'Rejected' => 'Afgewezen',
    'Reply' => 'Antwoorden',
    'Send' => 'Verzenden',
    'Subject' => 'Onderwerp',
    'The requested Comment does not exist.' => 'Deze reactie is onvindbaar',
    'This comment has been rejected.' => 'Deze reactie is afgewezen',
    'Update' => 'Bijwerken',
    'Update comment' => 'Reactie bijwerken',
    'Update self-created comment' => 'Eigen reactie bijwerken',
    'Updated At' => 'Bijgewerkt op',
    'Updated By' => 'Bijgewerkt door',
];
