<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<a href="{loginUrl}">Login</a> to comment' => '<a href="{loginUrl}">Login</a> om te reageren',
    '<a href="{loginUrl}">Login</a> to view comments' => '<a href="{loginUrl}">Login</a> om reacties te zien',
    'Accept' => 'Accepteer',
    'Accepted' => 'Geaccepteerd',
    'Body' => 'Inhoud',
    'Comment cannot be blank' => 'Reactie mag niet blanco zijn',
    'Comments' => 'Reacties',
    'Comments ({n,number})' => 'Reacties ({n,number})',
    'Created At' => 'Ingestuurd op',
    'Created By' => 'Ingestuurd door',
    'Delete' => 'Wissen',
    'Deleting Comment. Are you sure?' => 'Reactie wissen. Zeker weten?',
    'Edit' => 'Bewerken',
    'ID' => '',
    'My comment...' => 'Mijn reactie...',
    'My reply...' => 'Mijn antwoord...',
    'Pending' => 'Wachtrij',
    'Reject' => 'Afwijzen',
    'Rejected' => 'Afgewezen',
    'Reply' => 'Antwoorden',
    'Send' => 'Verzenden',
    'Subject' => 'Onderwerp',
    'The requested Comment does not exist.' => 'Deze reactie is onvindbaar',
    'This comment has been rejected.' => 'Deze reactie is afgewezen',
    'Update' => 'Bijwerken',
    'Updated At' => 'Bijgewerkt op',
    'Updated By' => 'Bijgewerkt door',
];
